<li class="nav-item  {{ Request::is('admin/list-members')?'open':''}}{{ Request::is('admin/create-member')?'open':''}}{{ Request::is('admin/edit-member/*')?'open':''}}{{ Request::is('admin/sort-ec-member')?'open':''}}{{ Request::is('admin/sort-ccc-member')?'open':''}}{{ Request::is('admin/sort-sc-member')?'open':''}}"> <a href="javascript:;" class="nav-link nav-toggle"> <i class="fa fa-user-tie"></i> <span class="title">Members</span> <span class="arrow {{ Request::is('admin/list-members')?'open':''}}{{ Request::is('admin/create-member')?'open':''}}{{ Request::is('admin/edit-member/*')?'open':''}}{{ Request::is('admin/sort-ec-member')?'open':''}}{{ Request::is('admin/sort-ccc-member')?'open':''}}{{ Request::is('admin/sort-sc-member')?'open':''}}"></span> </a>
    <ul class="sub-menu" style="{{ Request::is('admin/list-members')?'display: block':''}}{{ Request::is('admin/create-member')?'display: block':''}}{{ Request::is('admin/edit-member/*')?'display: block':''}}{{ Request::is('admin/sort-ec-member')?'display: block':''}}{{ Request::is('admin/sort-ccc-member')?'display: block':''}}{{ Request::is('admin/sort-sc-member')?'display: block':''}}">
        <li class="nav-item {{ Request::is('admin/list-members')?'active':''}}"> <a href="{{ route('list_members') }}" class="nav-link "> <span class="title">List Members</span> </a> </li>
        <li class="nav-item {{ Request::is('admin/create-member')?'active':''}}"> <a href="{{ route('create_member') }}" class="nav-link "> <span class="title">Add Members</span> </a> </li>
        <li class="nav-item {{ Request::is('admin/sort-ec-member')?'active':''}}"> <a href="{{ route('sort_ec_members') }}" class="nav-link "> <span class="title">Sort Executive Committee</span> </a> </li>
        <li class="nav-item {{ Request::is('admin/sort-ccc-member')?'active':''}}"> <a href="{{ route('sort_ccc_members') }}" class="nav-link "> <span class="title">Sort Camp Commandant & Coach</span> </a> </li>
{{--        <li class="nav-item {{ Request::is('admin/sort-oa-member')?'active':''}}"> <a href="{{ route('sort_oa_members') }}" class="nav-link "> <span class="title">Sort Office Administration</span> </a> </li>--}}
        <li class="nav-item {{ Request::is('admin/sort-sc-member')?'active':''}}"> <a href="{{ route('sort_sc_members') }}" class="nav-link "> <span class="title">Sort Sub Committee</span> </a> </li>
    </ul>
</li>